### ISSUE TITLE
Add dropdown option to Catalog List table

### ISSUE THREAD

**Issue by Developing-Developer2019** [Developing-Developer2019/LibraryManagementApp#38]
### All
- Add view option

### Librarian
- Add delete option
- Add Edit option

### Member
- Add Reserve option

**Comment by iimamul** [comment]
if the dropdown option is added to the `Option` column in the `Catalog List table`, will there be an additional button to save those options? Or the on-button option change will make those actions be executed?

**Comment by Developing-Developer2019** [comment]
> if the dropdown option is added to the `Option` column in the `Catalog List table`, will there be an additional button to save those options? Or the on-button option change will make those actions be executed?

Hi @iimamul sorry, I have only just seen your comment. The options are executable action links. 

I have already started on this work with it being a small task there are other issues made available today for pickup.

**Comment by iimamul** [comment]
Ok
